const menu =[
    {
    id: 1,
    image: "images/istockphoto-1220017909-170667a.jpeg",
    name: "maggi",
    category:"breakfast",
    Price: 40,
    description :"lorem",
},
{
    id:2,
    image: "images/Unknown.jpeg",
   name:"Apple",
    Price:100,
    category:"lunch",
    description:"lorem12",
},
{
    id:3,
    image: "images/Unknown2.jpeg",
    name:"Mango",
    Price:100,
    category:"evening",
    description:"lorem12",
},
{
    id:4,
    image: "images/Unknown.jpeg",
    name:"Banana",
    Price:100,
    category:"breakfast",
    description:"lorem12",
},
{
    id:5,
    image: "images/Unknown.jpeg",
    name:"Garlic",
    Price:100,
    id:"lunch",
    description:"lorem12",
},
{
    id:6,
    image: "images/Unknown.jpeg",
    name:"ooo",
    Price:100,
    category:"evening",
    description:"lorem12",
},
{
    id:7,
    image: "images/Unknown1.jpeg",
    name:"chilli",
    Price:100,
    category:"breakfast",
    description:"lorem12",
},
{
    id:8,
    image:"images/Unknown.jpeg",
    name:"papaiya ",
    Price:100,
    category:"lunch",
    description:"lorem12",
},
{
    id:9,
    image:"images/Unknown2.jpeg",
    name:"Lemon",
    Price:100,
    category:"dinner",
    description:"lorem12",
}
];

export default menu;